version: '3'

services:
  redis:
    image: "redis"
    ports:
    - "6379:6379"
    expose:
      - 6379
    restart: unless-stopped
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: site-info-compose
    container_name: site-info-compose
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379

    ports:
      - "3050:3050"

    expose:
      - 3050
    volumes:
      - .:/home/node/docker-app
      - node_modules:/home/node/docker-app/node_modules
    networks:
      - app-network
    command: npm run startdev

volumes:
  node_modules:
networks:
  app-network:
